# Use a base image with Java installed
FROM openjdk:11-jre-slim

# Set the working directory in the container
WORKDIR /app

# Copy the JAR file into the container
COPY jarfile.jar .

# Command to run the Java application
CMD ["java", "-jar", "jarfile.jar"]
